[build]
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "OPENAI_MODEL"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
